[package]
name = "upto_top"
version = "0.2.0"
authors = ["SAWADA Tadashi <cesare@mayverse.jp>"]

[[bin]]
name = "upto_top"
path = "src/main.rs"

[[bin]]
name = "list_tops"
path = "src/list_tops.rs"

[dependencies]
